require 'rake/clean'

task :mkdoc do
  sh "ruby conv_texi.rb"
  sh "yard doc -r ../README.md --title 'Ruby/MathGL document' '../lib/**/*.rb'"
end

task :default => :mkdoc

CLEAN.include %w[doc .yardoc]
