require 'rake/clean'

task :mkdoc do
  sh "ruby conv_texi.rb ~/2015/src/mathgl-2.3.2/texinfo/ ../lib/mathgl/doc/"
  sh "yard doc -r ../README.md --title 'Ruby/MathGL document' '../lib/**/*.rb'"
end

task :default => :mkdoc

CLEAN.include %w[doc .yardoc]
